### ISSUE TITLE
Nest.js usage results in TypeError: (0 , image_url_1.default) is not a function

### ISSUE THREAD

**Issue by stephenhmarsh** [sanity-io/image-url#61]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

Usage in Nest.js with pnpm results in error:
```
[Nest] 4705  - 10/10/2023, 11:29:34 PM   ERROR [ExceptionsHandler] (0 , image_url_1.default) is not a function
TypeError: (0 , image_url_1.default) is not a function
    at AppService.getHello (/Users/stephen/dev/sanity-image-url-bug/src/app.service.ts:13:27)
    at AppController.getHello (/Users/stephen/dev/sanity-image-url-bug/src/app.controller.ts:10:28)
    at /Users/stephen/dev/sanity-image-url-bug/node_modules/.pnpm/@nestjs+core@10.2.7_@nestjs+common@10.2.7_@nestjs+platform-express@10.2.7_reflect-metadata@0.1.13_rxjs@7.8.1/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at InterceptorsConsumer.intercept (/Users/stephen/dev/sanity-image-url-bug/node_modules/.pnpm/@nestjs+core@10.2.7_@nestjs+common@10.2.7_@nestjs+platform-express@10.2.7_reflect-metadata@0.1.13_rxjs@7.8.1/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:12:20)
    at /Users/stephen/dev/sanity-image-url-bug/node_modules/.pnpm/@nestjs+core@10.2.7_@nestjs+common@10.2.7_@nestjs+platform-express@10.2.7_reflect-metadata@0.1.13_rxjs@7.8.1/node_modules/@nestjs/core/router/router-execution-context.js:46:60
    at /Users/stephen/dev/sanity-image-url-bug/node_modules/.pnpm/@nestjs+core@10.2.7_@nestjs+common@10.2.7_@nestjs+platform-express@10.2.7_reflect-metadata@0.1.13_rxjs@7.8.1/node_modules/@nestjs/core/router/router-proxy.js:9:23
    at Layer.handle [as handle_request] (/Users/stephen/dev/sanity-image-url-bug/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/stephen/dev/sanity-image-url-bug/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/stephen/dev/sanity-image-url-bug/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/stephen/dev/sanity-image-url-bug/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/layer.js:95:5)
 ```

**To Reproduce**

Reproducable in this repo of a new Nest.js project: https://github.com/stephenhmarsh/sanity-image-url-bug

- clone
- pnpm install
- pnpm start
- navigate to `/` of the server (localhost:3000)

**Expected behavior**

The default export of the package should be a function that works.

**Screenshots**

**Which versions of Sanity are you using?**

```
@sanity/cli (global)  3.15.1 (latest: 3.18.0)
@sanity/image-url      1.0.2 (up to date)
```

**What operating system are you using?**

MacOS Sonoma 14.0 (23A344)

**Which versions of Node.js / npm are you running?**

Run `npm -v && node -v` in the terminal and copy-paste the result here.

Using `pnpm`

```bash
pnpm -v && node -v
8.9.0
v18.14.0
```

**Additional context**

**Security issue?**

Any security issues should be submitted directly to [security@sanity.io](mailto:security@sanity.io). In order to determine whether you are dealing with a security issue, ask yourself these two questions:

- Can I access something that's not mine, or something I shouldn't have access to?
- Can I disable something for other people? If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at [security@sanity.io](mailto:security@sanity.io.

**Comment by Rhym** [comment]
@stephenhmarsh 2 years on, did you ever resolve this? I have run into the same issue.

**Comment by Rhym** [comment]
If anyone comes across the same issue, I fixed this by adding:

`"esModuleInterop": true,`

to my `tsconfig.json`

**Comment by stephenhmarsh** [comment]
Thanks @Rhym - to be honest, I forgot when this started working for us, but we also ended up enabling that setting, and no longer have this issue. 👍
